import { VfsNode } from './types';

export function createInitialFileSystem(): VfsNode {
  const rootNode: VfsNode = {
    name: '',
    type: 'directory',
    mode: 0o755,
    owner: 'root',
    group: 'root',
    size: 4096,
    mtime: new Date(),
    children: {
      bin: {
        name: 'bin',
        type: 'directory',
        mode: 0o755,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          bash: { name: 'bash', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 1234384, mtime: new Date(), content: '#!/bin/sh binary ELF' },
          sh: { name: 'sh', type: 'symlink', mode: 0o777, owner: 'root', group: 'root', size: 4, mtime: new Date(), target: '/bin/bash' },
          ls: { name: 'ls', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 142144, mtime: new Date() },
          cp: { name: 'cp', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 153976, mtime: new Date() },
          mv: { name: 'mv', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 137880, mtime: new Date() },
          rm: { name: 'rm', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 113200, mtime: new Date() },
          cat: { name: 'cat', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 43352, mtime: new Date() },
          chmod: { name: 'chmod', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 63936, mtime: new Date() },
          chown: { name: 'chown', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 72128, mtime: new Date() },
          tar: { name: 'tar', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 489408, mtime: new Date() },
          grep: { name: 'grep', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 161880, mtime: new Date() },
          ps: { name: 'ps', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 125136, mtime: new Date() },
          kill: { name: 'kill', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 31256, mtime: new Date() },
        },
      },
      usr: {
        name: 'usr',
        type: 'directory',
        mode: 0o755,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          bin: {
            name: 'bin',
            type: 'directory',
            mode: 0o755,
            owner: 'root',
            group: 'root',
            size: 4096,
            mtime: new Date(),
            children: {
              find: { name: 'find', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 285408, mtime: new Date() },
              less: { name: 'less', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 178224, mtime: new Date() },
              which: { name: 'which', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 14752, mtime: new Date() },
              man: { name: 'man', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 110848, mtime: new Date() },
              env: { name: 'env', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 39120, mtime: new Date() },
              uptime: { name: 'uptime', type: 'file', mode: 0o755, owner: 'root', group: 'root', size: 31224, mtime: new Date() },
            },
          },
        },
      },
      home: {
        name: 'home',
        type: 'directory',
        mode: 0o755,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          student: {
            name: 'student',
            type: 'directory',
            mode: 0o755,
            owner: 'student',
            group: 'student',
            size: 4096,
            mtime: new Date(),
            children: {
              'notes.txt': {
                name: 'notes.txt',
                type: 'file',
                mode: 0o644,
                owner: 'student',
                group: 'student',
                size: 218,
                mtime: new Date(),
                content:
                  "=== LPIC-1 Study Notes ===\n- Remember that octal 750 means rwxr-x---\n- Inodes store file metadata, not the filename\n- Systemd targets replace SysVinit runlevels\n- Use grep -E for extended regular expressions\n",
              },
              'todo.md': {
                name: 'todo.md',
                type: 'file',
                mode: 0o644,
                owner: 'student',
                group: 'student',
                size: 154,
                mtime: new Date(),
                content:
                  "# Lab Todo List\n- [ ] Configure backup.sh permissions to 750\n- [ ] Extract errors from auth.log\n- [ ] Archive projects folder into tar.gz\n- [ ] Check crontab schedule\n",
              },
              '.bashrc': {
                name: '.bashrc',
                type: 'file',
                mode: 0o644,
                owner: 'student',
                group: 'student',
                size: 240,
                mtime: new Date(),
                content:
                  "# ~/.bashrc student environment\nexport PATH=$PATH:/home/student/scripts\nalias ll='ls -la'\nalias grep='grep --color=auto'\nexport EDITOR=nano\n",
              },
              scripts: {
                name: 'scripts',
                type: 'directory',
                mode: 0o755,
                owner: 'student',
                group: 'student',
                size: 4096,
                mtime: new Date(),
                children: {
                  'backup.sh': {
                    name: 'backup.sh',
                    type: 'file',
                    mode: 0o644, // Initial permission: rw-r--r--, needs 750 for lab!
                    owner: 'student',
                    group: 'student',
                    size: 342,
                    mtime: new Date(),
                    content:
                      "#!/bin/bash\n# Enterprise backup routine\nBACKUP_DIR=\"/var/backups\"\nDATE=$(date +%Y%m%d_%H%M%S)\necho \"[INFO] Starting archive of /home/student/projects...\"\ntar -czf \"${BACKUP_DIR}/projects_${DATE}.tar.gz\" /home/student/projects\necho \"[SUCCESS] Backup completed: projects_${DATE}.tar.gz\"\n",
                  },
                  'monitor.sh': {
                    name: 'monitor.sh',
                    type: 'file',
                    mode: 0o755,
                    owner: 'student',
                    group: 'student',
                    size: 185,
                    mtime: new Date(),
                    content:
                      "#!/bin/bash\necho \"=== System Health Check ===\"\nuptime\nfree -m\ndf -h /\n",
                  },
                },
              },
              projects: {
                name: 'projects',
                type: 'directory',
                mode: 0o755,
                owner: 'student',
                group: 'developers',
                size: 4096,
                mtime: new Date(),
                children: {
                  web: {
                    name: 'web',
                    type: 'directory',
                    mode: 0o755,
                    owner: 'student',
                    group: 'developers',
                    size: 4096,
                    mtime: new Date(),
                    children: {
                      'app.py': {
                        name: 'app.py',
                        type: 'file',
                        mode: 0o644,
                        owner: 'student',
                        group: 'developers',
                        size: 195,
                        mtime: new Date(),
                        content:
                          "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef index():\n    return 'Hello from LPI Training Server!'\n\nif __name__ == '__main__':\n    app.run(host='0.0.0.0', port=8080)\n",
                      },
                      'config.json': {
                        name: 'config.json',
                        type: 'file',
                        mode: 0o644,
                        owner: 'student',
                        group: 'developers',
                        size: 98,
                        mtime: new Date(),
                        content: '{\n  "environment": "production",\n  "port": 8080,\n  "max_workers": 4\n}\n',
                      },
                    },
                  },
                  'data.csv': {
                    name: 'data.csv',
                    type: 'file',
                    mode: 0o644,
                    owner: 'student',
                    group: 'developers',
                    size: 186,
                    mtime: new Date(),
                    content:
                      "id,username,role,status\n1,student,trainee,active\n2,alice,developer,active\n3,bob,sysadmin,active\n4,charlie,contractor,inactive\n5,dave,security,active\n",
                  },
                },
              },
            },
          },
        },
      },
      etc: {
        name: 'etc',
        type: 'directory',
        mode: 0o755,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          passwd: {
            name: 'passwd',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 480,
            mtime: new Date(),
            content:
              "root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nbin:x:2:2:bin:/bin:/usr/sbin/nologin\nsys:x:3:3:sys:/dev:/usr/sbin/nologin\nsync:x:4:65534:sync:/bin:/bin/sync\nstudent:x:1000:1000:Linux Student,,,:/home/student:/bin/bash\nalice:x:1001:1001:Alice Developer,,,:/home/alice:/bin/bash\nbob:x:1002:1002:Bob Sysadmin,,,:/home/bob:/bin/bash\nnginx:x:101:101:nginx web server,,,:/var/www:/usr/sbin/nologin\n",
          },
          group: {
            name: 'group',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 260,
            mtime: new Date(),
            content:
              "root:x:0:\ndaemon:x:1:\nsudo:x:27:student,bob\nstudent:x:1000:\ndevelopers:x:1001:alice,student\nsysadmin:x:1002:bob\nnginx:x:101:\n",
          },
          shadow: {
            name: 'shadow',
            type: 'file',
            mode: 0o640,
            owner: 'root',
            group: 'shadow',
            size: 320,
            mtime: new Date(),
            content:
              "root:$6$salt$hashedpassword:19820:0:99999:7:::\nstudent:$6$salt$hashedstudentpass:19820:0:99999:7:::\nalice:$6$salt$hashedalicepass:19820:0:99999:7:::\nbob:$6$salt$hashedbobpass:19820:0:99999:7:::\n",
          },
          hosts: {
            name: 'hosts',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 220,
            mtime: new Date(),
            content:
              "127.0.0.1\tlocalhost\n127.0.1.1\tlpi-lab.local lpi-lab\n192.168.1.10\tweb-prod-01\n192.168.1.20\tdb-primary-01\n192.168.1.50\tworkstation\n",
          },
          fstab: {
            name: 'fstab',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 380,
            mtime: new Date(),
            content:
              "# /etc/fstab: static file system information.\nUUID=4a8f9c12-3456-7890-abcd-ef0123456789 / ext4 defaults,noatime 0 1\nUUID=1234-ABCD /boot/efi vfat umask=0077 0 2\nUUID=9876-FEDC /home ext4 defaults 0 2\n/swapfile none swap sw 0 0\n",
          },
          'resolv.conf': {
            name: 'resolv.conf',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 92,
            mtime: new Date(),
            content: "nameserver 1.1.1.1\nnameserver 8.8.8.8\nsearch lpi-lab.local\n",
          },
          'os-release': {
            name: 'os-release',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 190,
            mtime: new Date(),
            content:
              "PRETTY_NAME=\"Debian GNU/Linux 12 (bookworm)\"\nNAME=\"Debian GNU/Linux\"\nVERSION_ID=\"12\"\nVERSION=\"12 (bookworm)\"\nID=debian\nHOME_URL=\"https://www.debian.org/\"\n",
          },
          hostname: {
            name: 'hostname',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 8,
            mtime: new Date(),
            content: "lpi-lab\n",
          },
          crontab: {
            name: 'crontab',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 420,
            mtime: new Date(),
            content:
              "SHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n\n# m h dom mon dow user  command\n17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly\n25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )\n47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )\n52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )\n0 2     * * *   student /home/student/scripts/backup.sh >/dev/null 2>&1\n",
          },
        },
      },
      var: {
        name: 'var',
        type: 'directory',
        mode: 0o755,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          log: {
            name: 'log',
            type: 'directory',
            mode: 0o755,
            owner: 'root',
            group: 'root',
            size: 4096,
            mtime: new Date(),
            children: {
              syslog: {
                name: 'syslog',
                type: 'file',
                mode: 0o640,
                owner: 'root',
                group: 'adm',
                size: 780,
                mtime: new Date(),
                content:
                  "Sep 20 10:00:01 lpi-lab CRON[1402]: (root) CMD (run-parts --report /etc/cron.hourly)\nSep 20 10:14:22 lpi-lab systemd[1]: Started User Manager for UID 1000.\nSep 20 10:14:25 lpi-lab sshd[1450]: Accepted publickey for student from 192.168.1.50 port 54320 ssh2\nSep 20 10:15:00 lpi-lab kernel: [  120.456] EXT4-fs (sda1): re-mounted. Opts: errors=remount-ro\nSep 20 10:30:12 lpi-lab systemd[1]: Starting Daily apt upgrade and clean activities...\nSep 20 10:30:15 lpi-lab systemd[1]: apt-daily-upgrade.service: Deactivated successfully.\nSep 20 11:00:01 lpi-lab CRON[1840]: (root) CMD (run-parts --report /etc/cron.hourly)\n",
              },
              'auth.log': {
                name: 'auth.log',
                type: 'file',
                mode: 0o640,
                owner: 'root',
                group: 'adm',
                size: 640,
                mtime: new Date(),
                content:
                  "Sep 20 10:14:25 lpi-lab sshd[1450]: Accepted publickey for student from 192.168.1.50 port 54320 ssh2\nSep 20 10:14:25 lpi-lab systemd-logind[412]: New session 3 of user student.\nSep 20 10:18:02 lpi-lab sudo:  student : TTY=pts/0 ; PWD=/home/student ; USER=root ; COMMAND=/usr/bin/apt update\nSep 20 10:22:15 lpi-lab sshd[1580]: Failed password for invalid user admin from 10.0.0.88 port 48912 ssh2\nSep 20 10:22:18 lpi-lab sshd[1582]: Failed password for invalid user admin from 10.0.0.88 port 48914 ssh2\nSep 20 10:25:01 lpi-lab sshd[1610]: Accepted publickey for bob from 192.168.1.51 port 52140 ssh2\n",
              },
              nginx: {
                name: 'nginx',
                type: 'directory',
                mode: 0o755,
                owner: 'root',
                group: 'adm',
                size: 4096,
                mtime: new Date(),
                children: {
                  'access.log': {
                    name: 'access.log',
                    type: 'file',
                    mode: 0o644,
                    owner: 'www-data',
                    group: 'adm',
                    size: 490,
                    mtime: new Date(),
                    content:
                      "192.168.1.50 - - [20/Sep/2026:10:15:02 +0000] \"GET / HTTP/1.1\" 200 612 \"-\" \"curl/7.88.1\"\n192.168.1.55 - - [20/Sep/2026:10:15:10 +0000] \"GET /api/status HTTP/1.1\" 200 48 \"-\" \"Mozilla/5.0\"\n10.0.0.12 - - [20/Sep/2026:10:16:44 +0000] \"POST /login HTTP/1.1\" 401 128 \"-\" \"python-requests/2.31.0\"\n192.168.1.50 - - [20/Sep/2026:10:20:00 +0000] \"GET /docs/lpic1 HTTP/1.1\" 200 2048 \"-\" \"curl/7.88.1\"\n",
                  },
                },
              },
            },
          },
          backups: {
            name: 'backups',
            type: 'directory',
            mode: 0o755,
            owner: 'root',
            group: 'root',
            size: 4096,
            mtime: new Date(),
            children: {},
          },
        },
      },
      tmp: {
        name: 'tmp',
        type: 'directory',
        mode: 0o1777,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          'session_dump.tmp': {
            name: 'session_dump.tmp',
            type: 'file',
            mode: 0o644,
            owner: 'student',
            group: 'student',
            size: 512,
            mtime: new Date(),
            content: "Temporary session cache dump\ntimestamp=1726839000\nstatus=cached\n",
          },
        },
      },
      root: {
        name: 'root',
        type: 'directory',
        mode: 0o700,
        owner: 'root',
        group: 'root',
        size: 4096,
        mtime: new Date(),
        children: {
          '.bashrc': {
            name: '.bashrc',
            type: 'file',
            mode: 0o644,
            owner: 'root',
            group: 'root',
            size: 180,
            mtime: new Date(),
            content: "# Root bash environment\nexport PS1='\\[\\e[1;31m\\]\\u@\\h:\\w#\\[\\e[0m\\] '\n",
          },
          'admin_notes.txt': {
            name: 'admin_notes.txt',
            type: 'file',
            mode: 0o600,
            owner: 'root',
            group: 'root',
            size: 140,
            mtime: new Date(),
            content: "Confidential server setup notes.\nDatabase master password is in vault.\nRun security audit with Lynis monthly.\n",
          },
        },
      },
    },
  };

  return rootNode;
}
