import {
  generateOfflineExplanation,
  PedagogicalMode,
  PedagogicalQuiz,
  PEDAGOGICAL_TOPICS,
  PedagogicalTopic,
} from '../data/pedagogicalExplanations';

export interface ExplanationResult {
  title: string;
  category: string;
  content: string;
  mode: PedagogicalMode;
  keyPoints?: string[];
  analogyTitle?: string;
  analogyStory?: string;
  terminalSnippet?: string;
  quiz?: PedagogicalQuiz;
  trapTitle?: string;
  dangerLevel?: 'high' | 'medium' | 'critical';
  howToAvoid?: string;
  isAiGenerated: boolean;
  source: 'local' | 'gemini';
  aiNotice?: string;
}

export async function fetchPedagogicalExplanation(
  topicQuery: string,
  mode: PedagogicalMode,
  context?: string,
  isFrench = true,
  requestAi = false
): Promise<ExplanationResult> {
  // If AI is requested, try server endpoint
  if (requestAi) {
    try {
      const response = await fetch('/api/explain-differently', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topicQuery,
          mode,
          context,
          language: isFrench ? 'fr' : 'en',
        }),
      });

      if (response.ok) {
        const data = await response.json();
        if (data && data.content) {
          return {
            title: data.title || topicQuery,
            category: data.category || (isFrench ? 'Explication IA Gemini' : 'Gemini AI Explanation'),
            content: data.content,
            mode,
            keyPoints: data.keyPoints,
            analogyTitle: data.analogyTitle,
            analogyStory: data.analogyStory,
            terminalSnippet: data.terminalSnippet,
            quiz: data.quiz,
            trapTitle: data.trapTitle,
            dangerLevel: data.dangerLevel || 'medium',
            howToAvoid: data.howToAvoid,
            isAiGenerated: true,
            source: 'gemini',
            aiNotice: isFrench ? 'Généré dynamiquement par Gemini 3.8 Flash' : 'Dynamically generated by Gemini 3.8 Flash',
          };
        }
      }
    } catch {
      // Graceful fallback below
    }
  }

  // 100% Offline Local pedagogical engine
  const offline = generateOfflineExplanation(topicQuery, mode, context, isFrench);
  return {
    title: offline.title,
    category: offline.category,
    content: offline.content,
    mode,
    keyPoints: offline.keyPoints,
    analogyTitle: offline.analogyTitle,
    analogyStory: offline.analogyStory,
    terminalSnippet: offline.terminalSnippet,
    quiz: offline.quiz,
    trapTitle: offline.trapTitle,
    dangerLevel: offline.dangerLevel,
    howToAvoid: offline.howToAvoid,
    isAiGenerated: false,
    source: 'local',
  };
}

export function getAllCuratedTopics(): PedagogicalTopic[] {
  return PEDAGOGICAL_TOPICS;
}
